/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiParseBriefDocumentRouteImport } from './routes/api.parse-brief-document'
import { Route as ApiOutboundCallRouteImport } from './routes/api.outbound-call'
import { Route as ApiMarketResearchRouteImport } from './routes/api.market-research'
import { Route as ApiMapsKeyRouteImport } from './routes/api.maps-key'
import { Route as ApiCallStatusRouteImport } from './routes/api.call-status'

const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseBriefDocumentRoute = ApiParseBriefDocumentRouteImport.update({
  id: '/api/parse-brief-document',
  path: '/api/parse-brief-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOutboundCallRoute = ApiOutboundCallRouteImport.update({
  id: '/api/outbound-call',
  path: '/api/outbound-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketResearchRoute = ApiMarketResearchRouteImport.update({
  id: '/api/market-research',
  path: '/api/market-research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapsKeyRoute = ApiMapsKeyRouteImport.update({
  id: '/api/maps-key',
  path: '/api/maps-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallStatusRoute = ApiCallStatusRouteImport.update({
  id: '/api/call-status',
  path: '/api/call-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/api/call-status': typeof ApiCallStatusRoute
  '/api/maps-key': typeof ApiMapsKeyRoute
  '/api/market-research': typeof ApiMarketResearchRoute
  '/api/outbound-call': typeof ApiOutboundCallRoute
  '/api/parse-brief-document': typeof ApiParseBriefDocumentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/api/call-status': typeof ApiCallStatusRoute
  '/api/maps-key': typeof ApiMapsKeyRoute
  '/api/market-research': typeof ApiMarketResearchRoute
  '/api/outbound-call': typeof ApiOutboundCallRoute
  '/api/parse-brief-document': typeof ApiParseBriefDocumentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/api/call-status': typeof ApiCallStatusRoute
  '/api/maps-key': typeof ApiMapsKeyRoute
  '/api/market-research': typeof ApiMarketResearchRoute
  '/api/outbound-call': typeof ApiOutboundCallRoute
  '/api/parse-brief-document': typeof ApiParseBriefDocumentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/api/call-status'
    | '/api/maps-key'
    | '/api/market-research'
    | '/api/outbound-call'
    | '/api/parse-brief-document'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaign'
    | '/api/call-status'
    | '/api/maps-key'
    | '/api/market-research'
    | '/api/outbound-call'
    | '/api/parse-brief-document'
  id:
    | '__root__'
    | '/'
    | '/campaign'
    | '/api/call-status'
    | '/api/maps-key'
    | '/api/market-research'
    | '/api/outbound-call'
    | '/api/parse-brief-document'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRoute: typeof CampaignRoute
  ApiCallStatusRoute: typeof ApiCallStatusRoute
  ApiMapsKeyRoute: typeof ApiMapsKeyRoute
  ApiMarketResearchRoute: typeof ApiMarketResearchRoute
  ApiOutboundCallRoute: typeof ApiOutboundCallRoute
  ApiParseBriefDocumentRoute: typeof ApiParseBriefDocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-brief-document': {
      id: '/api/parse-brief-document'
      path: '/api/parse-brief-document'
      fullPath: '/api/parse-brief-document'
      preLoaderRoute: typeof ApiParseBriefDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/outbound-call': {
      id: '/api/outbound-call'
      path: '/api/outbound-call'
      fullPath: '/api/outbound-call'
      preLoaderRoute: typeof ApiOutboundCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-research': {
      id: '/api/market-research'
      path: '/api/market-research'
      fullPath: '/api/market-research'
      preLoaderRoute: typeof ApiMarketResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maps-key': {
      id: '/api/maps-key'
      path: '/api/maps-key'
      fullPath: '/api/maps-key'
      preLoaderRoute: typeof ApiMapsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/call-status': {
      id: '/api/call-status'
      path: '/api/call-status'
      fullPath: '/api/call-status'
      preLoaderRoute: typeof ApiCallStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRoute: CampaignRoute,
  ApiCallStatusRoute: ApiCallStatusRoute,
  ApiMapsKeyRoute: ApiMapsKeyRoute,
  ApiMarketResearchRoute: ApiMarketResearchRoute,
  ApiOutboundCallRoute: ApiOutboundCallRoute,
  ApiParseBriefDocumentRoute: ApiParseBriefDocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
