/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMarketResearchRouteImport } from './routes/api.market-research'
import { Route as ApiOutboundCallRouteImport } from './routes/api.outbound-call'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketResearchRoute = ApiMarketResearchRouteImport.update({
  id: '/api/market-research',
  path: '/api/market-research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOutboundCallRoute = ApiOutboundCallRouteImport.update({
  id: '/api/outbound-call',
  path: '/api/outbound-call',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/market-research': typeof ApiMarketResearchRoute
  '/api/outbound-call': typeof ApiOutboundCallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/market-research': typeof ApiMarketResearchRoute
  '/api/outbound-call': typeof ApiOutboundCallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/market-research': typeof ApiMarketResearchRoute
  '/api/outbound-call': typeof ApiOutboundCallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/market-research' | '/api/outbound-call'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/market-research' | '/api/outbound-call'
  id: '__root__' | '/' | '/api/market-research' | '/api/outbound-call'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMarketResearchRoute: typeof ApiMarketResearchRoute
  ApiOutboundCallRoute: typeof ApiOutboundCallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-research': {
      id: '/api/market-research'
      path: '/api/market-research'
      fullPath: '/api/market-research'
      preLoaderRoute: typeof ApiMarketResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/outbound-call': {
      id: '/api/outbound-call'
      path: '/api/outbound-call'
      fullPath: '/api/outbound-call'
      preLoaderRoute: typeof ApiOutboundCallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMarketResearchRoute: ApiMarketResearchRoute,
  ApiOutboundCallRoute: ApiOutboundCallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
